"""
Django settings for financial project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TESTING = os.environ.get("TESTING", "") == "true"
PROJECT_CODENAME = "financial"
if TESTING:
    assert DEBUG, "You can only test with DEBUG enabled!"

if DEBUG:
    if TESTING:
        print("TESTING")
    else:
        print("DEBUG")

DEVELOPMENT = DEBUG and not TESTING

HOSTS = ["versa-emails.oziotecnologia.com"]

if DEVELOPMENT:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = HOSTS

CSRF_TRUSTED_ORIGINS = ["https://" + host for host in HOSTS]

MEDIA_URL = "media/"
if DEVELOPMENT:
    MEDIA_ROOT = "media/"
else:
    MEDIA_ROOT = f"/var/media/{PROJECT_CODENAME}"


SECRET_KEY = "django-insecure-=f^dje6)gpg@y3!mt4dmji-r(@ghfz#i$gptwnhmz=!0e^apg$"
if not DEVELOPMENT:
    SECRET_KEY = os.environ["SECRET_KEY"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cash_flow',
    'django_jinja'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'financial.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    {
        "BACKEND": "django_jinja.jinja2.Jinja2",
        "DIRS": [os.path.join(BASE_DIR, "financeiro/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "match_extension": ".j2",
            "globals": {
                "django_browser_reload_script": "django_browser_reload.jinja.django_browser_reload_script",
                "debug": DEBUG,
                "development": DEVELOPMENT,
            },
        },
    },
]

WSGI_APPLICATION = 'financial.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
