# Generated by Django 5.2.1 on 2025-06-04 01:40

import cash_flow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('name', models.TextField()),
                ('value', models.FloatField()),
                ('description', models.TextField()),
                ('type', models.TextField(verbose_name=cash_flow.models.FlowType)),
            ],
        ),
    ]
